basic:
    name: 'https://www.opploans.com batch 7'
    environments:
        production: 'https://www.opploans.com'
        staging: ''
        development: ''
    breakpoints:
        - 640
        - 1024
        - 1200
    pages:
        - /faqs/i-recently-paid-off-my-loan-when-can-i-reapply
        - /faqs/i-was-recently-denied-for-a-loan-when-can-i-reapply
        - /faqs/what-is-the-status-of-my-application
        - /faqs/how-long-does-it-take-to-get-a-decision
        - /faqs/is-bank-verification-safe-and-secure
        - /faqs/what-is-bank-verification-and-why-do-you-need-it
        - /faqs/will-my-credit-score-be-affected-if-i-apply
        - /faqs/how-do-i-know-if-ive-been-approved
        - /faqs/when-will-i-receive-my-funds
        - /faqs/im-self-employed-can-i-apply
    monitoring:
        days: {  }
        type: daily
        schedule_time: '06:30 AM'
        schedule_time_zone: Europe/London
        compare_with: last-production
        compare_with_fresh: production
advanced:
    mask: ''
    remove: "img[alt=\"OppLoans BBB Business Review\"]\n.footer__symbols"
    delay: 15
    scroll: true
    headers: {  }
    cookies: ''
    custom_js: ''
    custom_css: ''
    mock_content: {  }
    sensitivity: 30
    night_mode: false
    retina_images: false
    single_ip: false
    login:
        type: none
        click_element: false
        click_element_selector: ''
        login_url: ''
        username: ''
        password: ''
        username_selector: ''
        password_selector: ''
        submit_selector: ''
        after_login_selector: ''
    performance:
        workers_production: 30
        workers_nonproduction: 10
        workers_production_delay: 0
        workers_nonproduction_delay: 0
    stabilize: true
